### ISSUE TITLE
in kaggle

### ISSUE THREAD

**Issue by Soberaice** [xlang-ai/instructor-embedding#119]
Traceback (most recent call last):
  File "/kaggle/input/instructor/instructor-embedding-main/train.py", line 590, in <module>
    main()
  File "/kaggle/input/instructor/instructor-embedding-main/train.py", line 498, in main
    model = Instructor(real_name_or_path, cache_folder=model_args.cache_dir)
  File "/opt/conda/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 287, in __init__
    modules = self._load_sbert_model(
TypeError: Instructor._load_sbert_model() got an unexpected keyword argument 'local_files_only'

**Comment by BBC-Esq** [comment]
The owners of this repository don't update a new release on pypi.org.  You can download their most recent version or try my fork that incorporates additional parameters to choose from beyond what the most recent pull request here did...

https://github.com/BBC-Esq/instructor-embedding
