### ISSUE TITLE
NameError: name 'disabled_tqdm' is not defined

### ISSUE THREAD

**Issue by marybloodyzz** [xlang-ai/instructor-embedding#121]
As the title, has anyone got similar issue?
Traceback (most recent call last):
  File "/data//instructor-embedding/clustering.py", line 3, in <module>
    model = Instructor('hkunlp/instructor-large')
  File "/home/miniconda3/envs/instructor/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 95, in __init__
    modules = self._load_sbert_model(model_path)
  File "/data/instructor-embedding/InstructorEmbedding/instructor.py", line 530, in _load_sbert_model
    "tqdm_class": disabled_tqdm,
NameError: name 'disabled_tqdm' is not defined

FYI:
    def _load_sbert_model(self, model_path, token = None, cache_folder = None, revision = None, trust_remote_code = False):
        """
        Loads a full sentence-transformers model
        """
        # Taken mostly from: https://github.com/UKPLab/sentence-transformers/blob/66e0ee30843dd411c64f37f65447bb38c7bf857a/sentence_transformers/util.py#L544
        download_kwargs = {
            "repo_id": model_path,
            "revision": revision,
            "library_name": "sentence-transformers",
            "token": token,
            "cache_dir": cache_folder,
            "tqdm_class": disabled_tqdm,   (NameError: name 'disabled_tqdm' is not defined)
        }

**Comment by altria-zewei-wang** [comment]
Facing same problem, fixed with installing sentence transformer 2.3.0
